---
title: "MSDS 6303 Week 4 HW"
author: "Quincy Roundtree"
date: "6/6/2018"
output: 
  html_document:
  keep_md: True
---

# Install the fivethirtyeight package.

```

install.packages("fivethirtyeight")
```
# In the listing of Data sets in package ‘fivethirtyeight,’ assign the eighteenth data set to an object ‘df.’

```
df <- fivethirtyeight::college_all_ages
```

# Use a more detailed list of the data sets to write out the URL in a comment to the related news story.

```

data(package = "fivethirtyeight")
```

# https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/

# Using R command(s), give the dimensions and column names of this data frame.

```
	head(df)
	dim(df)
	colnames(df)
```

# Write an R command that gives you the column names of the data frame.  Right after that, write one that counts the number of columns but not rows. 

```
 unique(df$major_category)
 ncol(unique.data.frame(df))
```
# Generate a count of each unique major_category in the data frame.  I recommend using libraries to help.  I have demonstrated one briefly in live-session.  To be clear, this should look like a matrix or data frame containing the major_category and the frequency it occurs in the dataset.  Assign it to major_count.

```
count(df, df$major_category)
major_count <- count(df, df$major_category)
colnames(major_count) <- c("Category", "Count")
```

# To make things easier to read, put par(las=2) before your plot to make the text perpendicular to the axis.  Make a barplot of major_count.  Make sure to label the title with something informative (check the vignette if you need), label the x and y axis, and make it any color other than grey.  Assign the major_category labels to their respective bar.  Flip the barplot horizontally so that bars extend to the right, not upward.  All of these options can be done in a single pass of barplot(). 

```
par(las=2)
ct <- c(major_count$Count)
cou <-c(major_count$Category)
barplot(ct, names.arg = cou, main = "Count of Major Categories ", horiz = TRUE, col = "cyan")
```

# Write the fivethirtyeight data to a csv file.  Make sure that it does not have row labels.

```
write.csv(major_count, file = "Major Count.csv")
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
